site_name: APEX E2E TESTS 3
pages:
    - "Home": index.md
theme: readthedocs
theme_dir: theme
markdown_extensions:
    - admonition
    - def_list
    - grid_tables
extra:
    portalHostName: "https://apex.corp.yahoo.com"
